#!/usr/bin/bash

# Check if script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (with sudo)."
    exit
fi

# Update package manager 
dnf update -y

# Install desired packages
dnf install -y\
  arc-theme\
  brightnessctl\
  clang-tools-extra\
  curl\
  feh\
  flameshot\
  gcc\
  gimp\
  git\
  gparted\
  htop\
  i3\
  jq\
  lxappearance\
  make\
  neovim\
  pcmanfm\
  picom\
  python3\
  rofi\
  snapd\
  stow\
  tmux\
  vim\
  vlc\
  wget\
  xsel\
  zsh\

# install development tools 
dnf -y groupinstall "Development Tools"

# Output a message indicating the installation is complete
echo "Installation complete."
