#!/usr/bin/env zsh

# Check if script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (with sudo)."
    exit
fi

# Update package manager 
dnf update -y

# Install desired packages
dnf install -y \
  gcc \
  make \
  git \
  wget \
  curl \
  neovim \
  tmux \
  nodejs \
  vim \
  i3 \
  picom \
  lxappearance\
  rofi\
  feh\
  thunar\
  zsh\
  unrar\
  vlc\
  gparted\
  flameshot\
  brightnessctl\
  htop \
  net-tools \
  tree \
  jq \
  unzip \
  gzip \
  tar \
  python3 \
  python3-pip \
  python3-devel \

# Output a message indicating the installation is complete
echo "Installation complete."