#!/usr/bin/env bash 

# Check if script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (with sudo)."
    exit
fi

# Update package manager 
dnf update -y

# Install desired packages
dnf install -y\
  arc-theme\
  brightnessctl\
  clang-tools-extra\
  curl\
  fastfetch\
  feh\
  flameshot\
  gcc\
  git\
  htop\
  i3\
  jq\
  lxappearance\
  make\
  neovim\
  pcmanfm\
  python3\
  rofi\
  stow\
  tmux\
  vim\
  vlc\
  wget\
  xsel\
  zsh\
  luarocks\
  lua5.1\

# install development tools 
dnf5 install -y @development-tools

